### ISSUE TITLE
Issue with Video Frame Size and the Gameplay [Dark theme only]

### ISSUE THREAD

**Issue by devTipy** [simonsambolec/gameplay-plugin#1]
I absolutely love this idea but I'm getting a weird issue and glitch.

![image](https://user-images.githubusercontent.com/119019967/221080891-dcbd2cf8-2437-4520-adbf-6870f74bfb2d.png)

**Comment by bodhisingh** [comment]
UPDATE: If I change to Light theme, it works again. But this extension is incompatible with Dark theme.

**Comment by simonsambolec** [comment]
Thank you for the report, will check it out.

**Comment by simonsambolec** [comment]
Fixed, waiting for chrome store to accept the update.
