### ISSUE TITLE
Video gets cut off when using dark and light mode

### ISSUE THREAD

**Issue by CooperMoffatt** [simonsambolec/gameplay-plugin#2]
![image](https://user-images.githubusercontent.com/77920890/224976461-6cc7a8e9-ef83-4920-afd0-f97e15331106.png)

Video gets cut off when using dark and light mode you can see in this screen shot that you can't see the full screen button side

**Comment by CooperMoffatt** [comment]
The issue that I had initially encountered was that the YouTube video on my page was not properly aligned. After some investigation, I found that the issue was caused by the "width-fix.css" file. I was able to fix this issue by simply removing "width-fix.css".
It is worth noting that "width-fix.css" was designed to keep the YouTube box still, but not the actual video. Once I removed this file, the video was able to properly align on my page.


[width-fix.css](https://github.com/simonsambolec/gameplay-plugin/blob/main/css/width-fix.css)

**Comment by simonsambolec** [comment]
Hey,
I know what you are talking about, but the problem is that it might look OK on your screen, but mayority of people don't have a big screen so then they are only able to see one video.
So width-fix.css should contain some css that would always show both videos on all screen sizes. I still haven't figured it out tho after spending 30+ hours working on just this bug.

**Comment by CooperMoffatt** [comment]
Yeah it is a bit of a weird bug I don't really know what I am talking about when it comes to chrome extensions I just noticed that the width-fix.css locked the screen to a certain size, so I just thought that could be the problem and removing it fixed it for me

also, my screen size is 1080p 16:9

**Comment by simonsambolec** [comment]
Yeah I guess i will just remove it for now. Thanks for helping tho!

**Comment by CooperMoffatt** [comment]
I see what you mean by how it is meant to fix it now.

I think its just because the rest of youtube's CSS has been put in front of the video and that's what's causing you to not be able to see it and maybe if you moved the main video that would fix it not sure thought maybe ask StackOverflow 

Thank you for making this extension!

**Comment by simonsambolec** [comment]
For example, this is how it looks on a laptop:
![Screenshot_500](https://user-images.githubusercontent.com/7605117/227771123-58a9c857-a614-4b2f-b6aa-75f331500082.png)
But this is we would want it to look:
![Screenshot_501](https://user-images.githubusercontent.com/7605117/227771187-405ea9c1-f7c1-4e2c-941c-ea97a32c0f4a.png)
